// play/vue-project/src/App.vue
<script setup lang="ts">
import Home from './Home.vue'
import 'test-ui/lib/common.d.ts'

const asd = () => {
  // const type = typeof import('test-ui/lib')
}
</script>

<template>
  <div>
    <!-- <t-button msg="123">
      <div>123123</div>
    </t-button> -->
    <!-- <ReactButton msg="123"></ReactButton> -->
    <Home></Home>
    <y-button>333311111111</y-button>
    <!-- <n-button>naive-ui</n-button> -->
    <!-- <HelloWorld></HelloWorld> -->
    <!-- <button @click="a">测试</button> -->
  </div>
</template>

<style></style>

// play/react-project/src/app/page.tsx
"use client";

import { ReactButton } from "test-ui/lib/Button/TButton";

export default function Home() {
  // console.log(TButton());

  return (
    <main>
      <div>hallo,world</div>
      <div className="hallo">
        <div className="bg-red-200 w-60 h-60">123123</div>
        {/* <TButton></TButton> */}
        <ReactButton msg="垃圾Omi" class="bg-red-600 w-60 h-60 block">
          <div>123123123</div>
          <div>hallo,world</div>
        </ReactButton>
      </div>
    </main>
  );
}
